---
language: python
services: docker

env:
  global:
    - ROLE_NAME: memcached
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
