---
driver:
  name: docker
platforms:
  - name: ansible-role-memcached-1404
    image: ubuntu
    image_version: 14.04
    volume_mounts:
      - ${MOLECULE_APTPROXY_PATH}:/etc/apt/apt.conf.d/00aptproxy

  - name: ansible-role-memcached-1604
    image: ubuntu
    image_version: 16.04
    volume_mounts:
      - ${MOLECULE_APTPROXY_PATH}:/etc/apt/apt.conf.d/00aptproxy

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
