---
driver:
  name: docker
platforms:
  - name: ansible-role-memcached-1404
    image: ubuntu:14.04

  - name: ansible-role-memcached-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
